spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/city_driver
    username: postgres
    password: 211914
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  enabled: true
  baseline-version: 1
  schemas: public
  locations: classpath:db/migration
  sql-migration-suffixes: .sql
  baseline-on-migrate: true
  sql-migration-prefix: V

api:
  key:
    name: API_KEY
    value: fgfd1sdfg1513153&%&4@£dfsafsd32