spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/city_driver
    username: postgres
    password: 211914
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#spring:
#  datasource:
#    url: postgres://blsiodbbvfykzi:525158f73aa6122f44ccd6bf867dccb0434409f6df9b93149a4c50bd88c5f2ed@ec2-52-202-22-140.compute-1.amazonaws.com:5432/dempfgtbl03vmi
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true

flyway:
  enabled: true
  baseline-version: 1
  schemas: public
  locations: classpath:db/migration
  sql-migration-suffixes: .sql
  baseline-on-migrate: true
  sql-migration-prefix: V

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/car_drive?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password:
#  jpa:
#    hibernate:
#      format_sql: true
#      ddl-auto: update
#    show-sql: true
